### ISSUE TITLE
PackStack installation fails on newmaster/controller02

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#71] opened 2015-02-24 11:03 UTC
**Software:**
* r3
32dc107

**Component:**
cv_install_openstack

**Hardware:**
newmaster/controller02

**Test case:**
**Bug description:**
Packstack based openstack installation fails.

[root@openstack ~]# tail /var/log/xcat/xcat.log 
Traceback (most recent call last):
  File "/usr/bin/packstack", line 15, in <module>
    run_setup.main()
  File "/usr/lib/python2.7/site-packages/packstack/installer/run_setup.py", line 970, in main
    print output_messages.ERR_CHECK_LOG_FILE_FOR_MORE_INFO%(logFile)
UnboundLocalError: local variable 'logFile' referenced before assignment
sed: can't read /etc/nova/nova.conf: No such file or directory
sed: can't read /etc/openstack-dashboard/local_settings: No such file or directory
./cv_install_openstack: line 25: /root/keystonerc_admin: No such file or directory
./cv_install_openstack: line 26: nova: command not found

**Steps to reproduce:**
On newmaster
 nodeset controller02  osimage=centos7.0-x86_64-install-openstack

**Expected output:**

Working OpenStack installation on controller02

**Actual output:**

Failed OpenStack installation on controller02

**Comment by hansthen** [comment] 2015-02-24 11:43
Duplicate of #66

**Closed** 2015-02-24 11:44 UTC
Labels: duplicate
