### ISSUE TITLE
monitoring: web interface

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#199] opened 2015-04-29 10:05 UTC
**Software:** r3 9f5a966
**Component:** monitoring GUI 
**Hardware:** SM, controller02
**Test case:** 2.2.1
**Bug description:**
Errors launching monitoring web interface
**Steps to reproduce:**
After installing monitoring server on the controller,
```
firefox http://localhost:5003/monitoring &
```
**Expected output:**
Launching of monitoring web interface
**Actual output:**
Not found

**Comment by themisa** [comment] 2015-04-29 10:06
this works:
[root@controller ~]# firefox http://192.168.1.2:5003/monitoring &

**Comment by abhimukh** [comment] 2015-04-29 15:09
Currently the monitoring installation tool sets the web server to listen on the first IP address listed by hostname -I. This makes sense because we expect this interface to be on the external network.

**Comment by abhimukh** [comment] 2015-05-08 09:49
@themisa This is not a bug, it works as expected. Should be closed.
Reassigning to @themisa

**Closed** 2015-05-08 09:49 UTC
Labels: bug
