### ISSUE TITLE
cv_fly_clusterbats requires a package not available in the repos of a controller

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#482] opened 2015-10-12 15:20 UTC
`cv_fly_clusterbats` is part of EPEL which is not enabled in the repositories of a newly installed controller so the run_mpi.bats test in `/trinity/testing/clusterbats` fails since it can't find the package.

Enabled repos:

>[root@controller(magdeburg*) clusterbats]# yum repolist all
repo id                                                   repo name                                                   status
C7.0.1406-base/x86_64                                     CentOS-7.0.1406 - Base                                      disabled
C7.0.1406-centosplus/x86_64                               CentOS-7.0.1406 - CentOSPlus                                disabled
C7.0.1406-extras/x86_64                                   CentOS-7.0.1406 - Extras                                    disabled
C7.0.1406-fasttrack/x86_64                                CentOS-7.0.1406 - CentOSPlus                                disabled
C7.0.1406-updates/x86_64                                  CentOS-7.0.1406 - Updates                                   disabled
base/7/x86_64                                             CentOS-7 - Base                                             enabled: 8,652
base-debuginfo/x86_64                                     CentOS-7 - Debuginfo                                        disabled
base-source/7                                             CentOS-7 - Base Sources                                     disabled
centosplus/7/x86_64                                       CentOS-7 - Plus                                             enabled:    63
centosplus-source/7                                       CentOS-7 - Plus Sources                                     disabled
cr/7/x86_64                                               CentOS-7 - cr                                               disabled
extras/7/x86_64                                           CentOS-7 - Extras                                           enabled:   214
extras-source/7                                           CentOS-7 - Extras Sources                                   disabled
fasttrack/7/x86_64                                        CentOS-7 - fasttrack                                        disabled
updates/7/x86_64                                          CentOS-7 - Updates                                          enabled: 1,503
updates-source/7                                          CentOS-7 - Updates Sources                                  disabled

> [root@controller(magdeburg*) clusterbats]# yum search sshpass
Warning: No matches found for: sshpass
No matches found

### Fix

EPEL was installed by hand and sshpass could be installed after that.

**Comment by hansthen** [comment] 2015-10-13 10:44
Duplicate of #480

**Comment by hansthen** [comment] 2015-10-13 10:45
Duplicate of #473

**Closed** 2015-10-13 10:45 UTC
Labels: duplicate
