### ISSUE TITLE
docker images: not pushed to trinity compute nodes

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#338] opened 2015-07-06 08:07 UTC
* r5
7226080

**Test case:** 1.2.13

When we type "docker images" on the trinity compute nodes, no image available, so containers don't start.
When we pull the image on node, then service trinity status gives the error in ticket #333

**Comment by hansthen** [comment] 2015-07-06 14:25
This should be fixed with #333.

**Comment by themisa** [comment] 2015-07-09 09:08
NOT fixed in * r5
50b8019

```
[root@node001 ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
```

No docker images on trinity nodes

**Comment by themisa** [comment] 2015-07-09 09:18
Manual workaround:
```
[root@node001 ~]# docker pull controller:5050/trinity
Trying to pull repository controller:5050/trinity ...
ef2d5b4cac10: Download complete 
f1b10cd84249: Download complete 
c852f6d61e65: Download complete 
7322fbe74aa5: Download complete 
78a9b59de684: Download complete 
6bbab4dccb65: Download complete 
f1242ea50d79: Download complete 
ea77bce777ff: Download complete 
5d9952294db4: Download complete 
38878c134ca0: Download complete 
356eef5a5e9b: Download complete 
9e8d9be61a8f: Download complete 
488a991bfd5e: Download complete 
a4afb0101fe5: Download complete 
Status: Downloaded newer image for controller:5050/trinity:latest
```

**Comment by themisa** [comment] 2015-07-09 09:57
service trinity restart works

**Comment by themisa** [comment] 2015-07-09 12:49
note: this issue NOT present in r5_features branch

**Comment by hansthen** [comment] 2015-07-13 08:49
Duplicate of #333

**Comment by themisa** [comment] 2015-07-15 11:43
stil an issue
more info:
```
root@node001 ~]# service docker status
Redirecting to /bin/systemctl status  docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
  Drop-In: /usr/lib/systemd/system/docker.service.d
           remote-fs.conf, ulimit.conf
   Active: active (running) since Tue 2015-07-14 17:05:06 CEST; 20h ago
     Docs: http://docs.docker.com

 Main PID: 1565 (docker)
   CGroup: /system.slice/docker.service
           1565 /usr/bin/docker -d --insecure-registry controller:5050 --insecure-registry controller:5050 --bip=10.146.255.254/16 --fixed-cidr=10.146.255.255/16 --selinux-enabled

Jul 15 13:42:32 node001.cluster docker[1565]: time="2015-07-15T13:42:32+02:00" level=info msg="-job image_inspect(trinity) = ERR (1)"
Jul 15 13:42:32 node001.cluster docker[1565]: time="2015-07-15T13:42:32+02:00" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: trinity"
Jul 15 13:42:32 node001.cluster docker[1565]: time="2015-07-15T13:42:32+02:00" level=error msg="HTTP Error: statusCode=404 No such image: trinity"
Jul 15 13:42:52 node001.cluster docker[1565]: time="2015-07-15T13:42:52+02:00" level=info msg="GET /v1.18/info"
Jul 15 13:42:52 node001.cluster docker[1565]: time="2015-07-15T13:42:52+02:00" level=info msg="+job info()"
Jul 15 13:42:52 node001.cluster docker[1565]: time="2015-07-15T13:42:52+02:00" level=info msg="+job subscribers_count()"
Jul 15 13:42:52 node001.cluster docker[1565]: time="2015-07-15T13:42:52+02:00" level=info msg="-job subscribers_count() = OK (0)"
Jul 15 13:42:52 node001.cluster docker[1565]: time="2015-07-15T13:42:52+02:00" level=info msg="+job registry_config()"
Jul 15 13:42:52 node001.cluster docker[1565]: time="2015-07-15T13:42:52+02:00" level=info msg="-job registry_config() = OK (0)"
Jul 15 13:42:52 node001.cluster docker[1565]: time="2015-07-15T13:42:52+02:00" level=info msg="-job info() = OK (0)"
```

**Comment by hansthen** [comment] 2015-07-17 12:37
When running this in r5 I get a different error message:
```
[root@node001 ~]# systemctl status trinity
trinity.service - LSB: start and stop trinity
   Loaded: loaded (/etc/rc.d/init.d/trinity)
   Active: failed (Result: exit-code) since Fri 2015-07-17 14:30:31 CEST; 1min 40s ago
  Process: 1986 ExecStart=/etc/rc.d/init.d/trinity start (code=exited, status=1/FAILURE)

Jul 17 14:30:30 node001.cluster trinity[1986]: f1b10cd84249: Pulling metadata
Jul 17 14:30:30 node001.cluster trinity[1986]: f1b10cd84249: Pulling fs layer
Jul 17 14:30:30 node001.cluster trinity[1986]: f1b10cd84249: Error downloading dependent layers
Jul 17 14:30:30 node001.cluster trinity[1986]: cbb4b2409e0e: Error pulling image (latest) from controller:5050/trinity, endpoint: http://controller:5050/v1/, Driver devicemapper failed to create image rootfs f1b10cd842498c23d20...
Jul 17 14:30:30 node001.cluster trinity[1986]: cbb4b2409e0e: Error pulling image (latest) from controller:5050/trinity, Driver devicemapper failed to create image rootfs f1b10cd842498c23d206ee0cbeaa9de8d2ae09ff3...9 already exists
Jul 17 14:30:30 node001.cluster trinity[1986]: time="2015-07-17T14:30:30+02:00" level=fatal msg="Error pulling image (latest) from controller:5050/trinity, Driver devicemapper failed to create image rootfs f1b10cd842498c23d206e...
Jul 17 14:30:31 node001.cluster trinity[1986]: Error: No such image or container: trinity
Jul 17 14:30:31 node001.cluster systemd[1]: trinity.service: control process exited, code=exited status=1
Jul 17 14:30:31 node001.cluster systemd[1]: Failed to start LSB: start and stop trinity.
Jul 17 14:30:31 node001.cluster systemd[1]: Unit trinity.service entered failed state.
```

**Comment by hansthen** [comment] 2015-07-17 12:43
There turns out to be a problem with removing a stale container on node001.

Driver devicemapper failed to remove root filesystem c841352956a94accb140dbc66a57cb9e04a656e7a2d1dead800c65677772cccd

**Comment by hansthen** [comment] 2015-07-17 13:38
I think it is caused by our LVM script. Since docker (and trinity) are started before the postscripts run, the script copies a running /var/lib/docker into a different location. It appears this confuses docker. A workaround appears to be 
1. stop docker
2. rm /var/lib/docker
3. start docker
4. (re)start trinity

But this only works until the next reboot.

**Comment by hansthen** [comment] 2015-07-17 19:27
Weird. These files should be the same.
```
[root@master trinity]# diff /trinity/controller/rootimg/trinity/compute/rootimg/etc/rc.d/init.d/trinity /trinity/compute/rootimg/etc/rc.d/init.d/trinity
36,37c36
<     #for VC in vc-{a..l}; do
<     for VC in $(ls /cluster | grep "^vc-"); do
---
>     for VC in vc-{a..l}; do
75c74,75
<     read ETH1 ETH2 ETH3 <<<$(ls /sys/class/net/ | grep "^e" | sort | head -3)
---
>     # Fix for 229
>     ETH1=$(ip route | grep default | awk '{print $5}' | head -1)
127,128c127,128
<     state=$(docker inspect --format='{{.State.Running}}' trinity 2>/dev/null)
<     test -z $state || $state = true
---
>     state=$(docker inspect --format='{{.State.Running}}' trinity)
>     test -n "$state" -a "$state" = true
```

**Comment by hansthen** [comment] 2015-07-17 19:39
Fix was not present in r5 because r4_fixes had not been merged yet.

**Comment by hansthen** [comment] 2015-07-21 20:37
```
[root@node001 ~]# docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
controller:5050/trinity   latest              4755b28bde38        52 minutes ago      698.1 MB
```

**Closed** 2015-07-21 20:38 UTC
Labels: ASAP, bug
