### ISSUE TITLE
warnings when generating compute image

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#52] opened 2015-02-12 10:42 UTC
Not sure if its a bug, just documenting here:

genimage -o centos7.0 -a x86_64 -p compute

Enter the dracut mode. Dracut version: 033. Dracut directory: dracut_033.
Note: Forwarding request to 'systemctl enable rdma.service'.
ln -s '/usr/lib/systemd/system/rdma.service' '/etc/systemd/system/sysinit.target.wants/rdma.service'
Note: Forwarding request to 'systemctl enable ntpd.service'.
ln -s '/usr/lib/systemd/system/ntpd.service' '/etc/systemd/system/multi-user.target.wants/ntpd.service'
error reading information on service slurm: No such file or directory
error reading information on service munge: No such file or directory
install: cannot stat '/etc/munge/munge.key': No such file or directory
chown: cannot access '/etc/munge/munge.key': No such file or directory
install: cannot stat '/etc/slurm/slurm.conf': No such file or directory
install: cannot stat '/usr/share/Modules/init/.modulespath': No such file or directory
Note: Forwarding request to 'systemctl enable nslcd.service'.
ln -s '/usr/lib/systemd/system/nslcd.service' '/etc/systemd/system/multi-user.target.wants/nslcd.service'

Try to load drivers: pps_core i2c-core ptp libcrc32c mdio dca i2c-algo-bit mlx4_core virtio virtio_ring tg3 bnx2 bnx2x e1000 e1000e igb mlx4_en virtio_net be2net ext3 ext4 to initrd.
No '/dev/log' or 'logger' included for syslog logging
Turning off host-only mode: '/sys' is not mounted!
Turning off host-only mode: '/proc' is not mounted!
Turning off host-only mode: '/run' is not mounted!
Turning off host-only mode: '/dev' is not mounted!
the initial ramdisk for stateless is generated successfully.
Try to load drivers: pps_core i2c-core ptp libcrc32c mdio dca i2c-algo-bit mlx4_core virtio virtio_ring tg3 bnx2 bnx2x e1000 e1000e igb mlx4_en virtio_net be2net ext3 ext4 to initrd.
No '/dev/log' or 'logger' included for syslog logging
Turning off host-only mode: '/sys' is not mounted!
Turning off host-only mode: '/proc' is not mounted!
Turning off host-only mode: '/run' is not mounted!
Turning off host-only mode: '/dev' is not mounted!
the initial ramdisk for statelite is generated successfully.

**Comment by hansthen** [comment] 2015-02-16 18:09
These errors are caused by having slurm packages in the compute image packagelist. As stated we want to move the slurm images out of the default compute image. We need to define a special image type that runs an HPC bare metal node. (suggestion, shall we call that an hpc image?)

**Comment by hansthen** [comment] 2015-02-18 17:15
I adapted the package list. Assigned to Themis for re-testing.

**Comment by themisa** [comment] 2015-02-26 15:35
Still getting these warnings:

Enter the dracut mode. Dracut version: 033. Dracut directory: dracut_033.
Note: Forwarding request to 'systemctl enable rdma.service'.
ln -s '/usr/lib/systemd/system/rdma.service' '/etc/systemd/system/sysinit.target.wants/rdma.service'
Note: Forwarding request to 'systemctl enable ntpd.service'.
ln -s '/usr/lib/systemd/system/ntpd.service' '/etc/systemd/system/multi-user.target.wants/ntpd.service'
error reading information on service slurm: No such file or directory
error reading information on service munge: No such file or directory
Note: Forwarding request to 'systemctl disable avahi-daemon.service'.
rm '/etc/systemd/system/multi-user.target.wants/avahi-daemon.service'
rm '/etc/systemd/system/sockets.target.wants/avahi-daemon.socket'
rm '/etc/systemd/system/dbus-org.freedesktop.Avahi.service'
install: cannot stat '/etc/munge/munge.key': No such file or directory
chown: cannot access '/etc/munge/munge.key': No such file or directory
install: cannot stat '/etc/slurm/slurm.conf': No such file or directory
install: cannot stat '/usr/share/Modules/init/.modulespath': No such file or directory
Note: Forwarding request to 'systemctl enable nslcd.service'.
ln -s '/usr/lib/systemd/system/nslcd.service' '/etc/systemd/system/multi-user.target.wants/nslcd.service'
Try to load drivers: pps_core i2c-core ptp libcrc32c mdio dca i2c-algo-bit mlx4_core virtio virtio_ring tg3 bnx2 bnx2x e1000 e1000e igb mlx4_en virtio_net be2net ext3 ext4 to initrd.
No '/dev/log' or 'logger' included for syslog logging
Turning off host-only mode: '/sys' is not mounted!
Turning off host-only mode: '/proc' is not mounted!
Turning off host-only mode: '/run' is not mounted!
Turning off host-only mode: '/dev' is not mounted!
the initial ramdisk for stateless is generated successfully.
Try to load drivers: pps_core i2c-core ptp libcrc32c mdio dca i2c-algo-bit mlx4_core virtio virtio_ring tg3 bnx2 bnx2x e1000 e1000e igb mlx4_en virtio_net be2net ext3 ext4 to initrd.
No '/dev/log' or 'logger' included for syslog logging
Turning off host-only mode: '/sys' is not mounted!
Turning off host-only mode: '/proc' is not mounted!
Turning off host-only mode: '/run' is not mounted!
Turning off host-only mode: '/dev' is not mounted!
the initial ramdisk for statelite is generated successfully.

**Comment by hansthen** [comment] 2015-02-26 18:49
We also need to remove some lines from the compute postinstall script.

**Closed** 2015-03-31 13:51 UTC

**Comment by themisa** [comment] 2015-05-22 08:53
tested in *master_installer 1030300.
No more slurm related warnings.
