### ISSUE TITLE
After deploying a controller the repositories need to be cleaned

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#472] opened 2015-10-08 11:28 UTC
### Issue

The controller still has the old pmaster as one of its repositories:

```
[root@controller(unknown*) ~]# yum clean all
Loaded plugins: fastestmirror
Cleaning repos: local-centos7.0-x86_64-x86_64 xcat-otherpkgs0
Cleaning up everything
Cleaning up list of fastest mirrors
[root@controller(unknown*) ~]# yum install vim
Loaded plugins: fastestmirror
http://192.168.1.254/install/centos7.0/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://192.168.1.254/install/centos7.0/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30028 milliseconds')
Trying other mirror.
http://192.168.1.254/install/centos7.0/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://192.168.1.254/install/centos7.0/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30028 milliseconds')
Trying other mirror.
http://192.168.1.254/install/centos7.0/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://192.168.1.254/install/centos7.0/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30028 milliseconds')
Trying other mirror.
```

These should not be enabled.

```
[root@controller(unknown*) yum.repos.d]# cat local-repository.repo 
[local-centos7.0-x86_64-x86_64]
name=xCAT configured yum repository for centos7.0/x86_64/x86_64
baseurl=http://192.168.1.254/install/centos7.0/x86_64/
enabled=1
gpgcheck=0
[root@controller(unknown*) yum.repos.d]# cat xCAT-otherpkgs0.repo 
[xcat-otherpkgs0]
name=xcat-otherpkgs0
baseurl=http://192.168.1.254/install/post/otherpkgs/centos7.0/x86_64/.
enabled=1
gpgcheck=0
```

**Fix**

```
[root@controller(unknown*) yum.repos.d]# cat local-repository.repo 
[local-centos7.0-x86_64-x86_64]
name=xCAT configured yum repository for centos7.0/x86_64/x86_64
baseurl=http://192.168.1.254/install/centos7.0/x86_64/
enabled=0
gpgcheck=0
[root@controller(unknown*) yum.repos.d]# cat xCAT-otherpkgs0.repo 
[xcat-otherpkgs0]
name=xcat-otherpkgs0
baseurl=http://192.168.1.254/install/post/otherpkgs/centos7.0/x86_64/.
enabled=0
gpgcheck=0
```

**Comment by hansthen** [comment] 2015-10-13 10:46
Duplicate of #473

**Closed** 2015-10-26 06:06 UTC
Labels: bug, duplicate
