### ISSUE TITLE
modules (/trinity/clustervision) not available in docker containers

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#491] opened 2015-10-16 09:27 UTC
[root@node001 ~]# /trinity/report
**Version:** r6_fixes fd4dfcc
**Environment:** dmaster

```
[root@c001 /]# module avail

------------------------------------------------------------- /usr/share/Modules/modulefiles -------------------------------------------------------------
dot         module-git  module-info modules     null        use.own
```

**Comment by hansthen** [comment] 2015-11-11 22:19
duplicate of #505

**Closed by hansthen** 2015-11-11 22:19 UTC
Labels: bug, duplicate
