### ISSUE TITLE
Trinity compute netboot image has invalid repositories listed

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#480] opened 2015-10-12 11:37 UTC
### Issue:

Trying to install compute nodes with `nodeset n00[1-4] osimage=centos7-x86_64-netboot-trinity` after a fresh controller deployment resulted in:

> Oct 12 13:24:09 n001 xcatpostinit: http://192.168.1.254/install/centos7.0/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed connect to 192.168.1.254:80; No route to host"
Oct 12 13:24:09 n001 xcatpostinit: Trying other mirror.
Oct 12 13:24:11 controller xCAT[24556]: xCAT: Allowing nodestat to compute for root from localhost
Oct 12 13:24:11 n001 trinity: Host n001.vc-a not found: 3(NXDOMAIN)
Oct 12 13:24:11 n001 trinity: Could not determine cluster membership for this node. Sleeping now.
Oct 12 13:24:12 n001 xcatpostinit: http://192.168.1.254/install/centos7.0/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed connect to 192.168.1.254:80; No route to host"
Oct 12 13:24:12 n001 xcatpostinit: Trying other mirror.
Oct 12 13:24:13 controller xCAT[24567]: xCAT: Allowing nodestat to compute for root from localhost
Oct 12 13:24:15 n001 xcatpostinit: http://192.168.1.254/install/centos7.0/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed connect to 192.168.1.254:80; No route to host"
Oct 12 13:24:15 n001 xcatpostinit: Trying other mirror.

Looking at `/install/netboot/centos7/x86_64/trinity/rootimg` in the `etc/yum.repos.d/local-repository.repo` we see that the repositories address is wrong:

>[root@controller(magdeburg*) rootimg]# cat etc/yum.repos.d/local-repository.repo 
[local-centos7.0-x86_64-x86_64]
name=xCAT configured yum repository for centos7.0/x86_64/x86_64
baseurl=http://192.168.1.254/install/centos7.0/x86_64/
enabled=1
gpgcheck=0

### Fix:

Replace address with proper controller address (10.141.255.254), repack the image and restart the process.

### Trinity release

[root@controller(magdeburg*) rootimg]# cat /trinity/version 
* (detached from vMagdeburg)
269bf23

**Comment by brunopereira81** [comment] 2015-10-12 12:41
This is related to https://github.com/clustervision/trinity/issues/480 because the repositories that are invalid in the controller are then copied to the image breaking the setup in the trinity netboot image.

**Comment by hansthen** [comment] 2015-10-13 10:45
Duplicate of #473

**Closed** 2015-10-13 10:45 UTC
Labels: ASAP, bug, duplicate
