### ISSUE TITLE
Login node: after reboot hostname needs to be reset

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#347] opened 2015-07-10 11:59 UTC
It needs to be login.vc-a

**Comment by abhimukh** [comment] 2015-07-27 08:20
Duplicate of #334

**Comment by abhimukh** [comment] 2015-07-28 08:54
Please see my comments for #334. Assigning to @themisa for testing.

**Comment by hansthen** [comment] 2015-08-04 07:27
From what I understand, this problem did not go away. We need to find a solution so that after a reboot of the login node, customers do not need to set the hostname manually.

**Comment by abhimukh** [comment] 2015-08-04 11:48
Fixed in r5_fixes : 68957b3
Please see my comments for #334. 
Reassigning to @themisa for testing.

**Comment by themisa** [comment] 2015-08-14 07:38
See comments on #334. hostname on reboot is "login".

**Closed by themisa** 2015-08-14 07:38 UTC
Labels: bug, duplicate, QA verified
