### ISSUE TITLE
Login node: nodes sometimes boot without network

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#366] opened 2015-07-23 16:38 UTC
**Version:** r4_fixes cdaf89b
**Environment:** master

If that happens, you will see the following in the console-log.
```
cloud-init[799]: Cloud-init v. 0.7.5 running 'init' at Thu, 23 Jul 2015 16:36:45 +0000. Up 14.67 seconds.
cloud-init[799]: ci-info: +++++++++++++++++++++++Net device info++++++++++++++++++++++++
cloud-init[799]: ci-info: +--------+-------+-----------+-----------+-------------------+
cloud-init[799]: ci-info: | Device |   Up  |  Address  |    Mask   |     Hw-Address    |
cloud-init[799]: ci-info: +--------+-------+-----------+-----------+-------------------+
cloud-init[799]: ci-info: |  lo:   |  True | 127.0.0.1 | 255.0.0.0 |         .         |
cloud-init[799]: ci-info: | eth0:  | False |     .     |     .     | fa:16:3e:54:2b:ea |
cloud-init[799]: ci-info: +--------+-------+-----------+-----------+-------------------+
cloud-init[799]: ci-info: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Route info failed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by hansthen** [comment] 2015-07-23 17:29
Earlier I see this: 
[[1;31mFAILED[0m] Failed to start LSB: Bring up/down networking.
See 'systemctl status network.service' for details.

It seems to be an internal problem in the image. We may need to use the console to investigate further.

**Comment by hansthen** [comment] 2015-07-23 17:47
The problems seems to be that 
/etc/sysconfig/network-scripts/ifcfg-eth0 seems to be empty.

**Comment by hansthen** [comment] 2015-07-23 20:57
If an ip address and (default) route to eth0 is added to the system via the system, we can access the outside world.

**Comment by hansthen** [comment] 2015-07-23 21:27
It looks like our nodes are booted without an associated volume. However, I did notice that changes were persistent across reboots.

**Comment by hansthen** [comment] 2015-07-23 21:33
The output from a succesful boot:
```
         Starting LSB: Bring up/down networking...
[[32m  OK  [0m] Started Dump dmesg to /var/log/dmesg.
[[32m  OK  [0m] Started Permit User Sessions.
         Starting Command Scheduler...
[[32m  OK  [0m] Started Command Scheduler.
         Starting Serial Getty on ttyS0...
[[32m  OK  [0m] Started Serial Getty on ttyS0.
         Starting Getty on tty1...
[[32m  OK  [0m] Started Getty on tty1.
[[32m  OK  [0m] Reached target Login Prompts.
[[32m  OK  [0m] Started System Logging Service.
[[32m  OK  [0m] Started NTP client/server.
[[32m  OK  [0m] Started Login Service.
[[32m  OK  [0m] Started OpenSSH Server Key Generation.
[[32m  OK  [0m] Started Dynamic System Tuning Daemon.
cloud-init[470]: Cloud-init v. 0.7.5 running 'init-local' at Thu, 23 Jul 2015 21:24:11 +0000. Up 9.02 seconds.
[[32m  OK  [0m] Started Initial cloud-init job (pre-networking).
[[32m  OK  [0m] Started LSB: Bring up/down networking.
[[32m  OK  [0m] Reached target Network.
         Starting Initial cloud-init job (metadata service crawler)...
         Starting Postfix Mail Transport Agent...
         Starting OpenSSH server daemon...
[[32m  OK  [0m] Started OpenSSH server daemon.
cloud-init[756]: Cloud-init v. 0.7.5 running 'init' at Thu, 23 Jul 2015 21:24:13 +0000. Up 10.87 seconds.
cloud-init[756]: ci-info: ++++++++++++++++++++++++++Net device info+++++++++++++++++++++++++++
cloud-init[756]: ci-info: +--------+------+--------------+---------------+-------------------+
cloud-init[756]: ci-info: | Device |  Up  |   Address    |      Mask     |     Hw-Address    |
cloud-init[756]: ci-info: +--------+------+--------------+---------------+-------------------+
cloud-init[756]: ci-info: |  lo:   | True |  127.0.0.1   |   255.0.0.0   |         .         |
cloud-init[756]: ci-info: | eth0:  | True | 192.168.32.4 | 255.255.252.0 | fa:16:3e:7f:a6:86 |
cloud-init[756]: ci-info: +--------+------+--------------+---------------+-------------------+
cloud-init[756]: ci-info: ++++++++++++++++++++++++++++++++Route info+++++++++++++++++++++++++++++++++
cloud-init[756]: ci-info: +-------+--------------+--------------+---------------+-----------+-------+
cloud-init[756]: ci-info: | Route | Destination  |   Gateway    |    Genmask    | Interface | Flags |
cloud-init[756]: ci-info: +-------+--------------+--------------+---------------+-----------+-------+
cloud-init[756]: ci-info: |   0   |   0.0.0.0    | 192.168.32.3 |    0.0.0.0    |    eth0   |   UG  |
cloud-init[756]: ci-info: |   1   | 192.168.32.0 |   0.0.0.0    | 255.255.252.0 |    eth0   |   U   |
cloud-init[756]: ci-info: +-------+--------------+--------------+---------------+-----------+-------+
[[32m  OK  [0m] Started Postfix Mail Transport Agent.

CentOS Linux 7 (Core)
Kernel 3.10.0-229.el7.x86_64 on an x86_64
```

**Comment by abhimukh** [comment] 2015-07-27 08:39
@hansthen Could you recreate this issue? The file: `/etc/sysconfig/network-scripts/ifcfg-eth0`. it should look something like this
```
DEVICE="eth0"
BOOTPROTO="dhcp"
ONBOOT="yes"
TYPE="Ethernet"
USERCTL="yes"
PEERDNS="no"
IPV6INIT="no"
PERSISTENT_DHCLIENT="1"
```
As far as the associated volume is concerned, indeed the login node instances are not booted with any associated persistent block device. However, they __are__ booted with ephemeral storage (managed by nova). The ephemeral storage is persistent across instance reboot but will not survive instance termination. But, I don't understand how this is related to the issue.

**Comment by hansthen** [comment] 2015-07-27 15:56
I saw this when I rebooted the OpenStack node. Does a reboot of the OpenStack node mess up ephemeral storage?

**Comment by abhimukh** [comment] 2015-07-29 10:35
@hansthen Reboot does not mess up ephemeral storage.

**Comment by abhimukh** [comment] 2015-07-29 10:42
I have noticed this issue in the past, when instances are deleted and created in quick succession. It is very likely because the database does not get updated in time - if the newly created instance is trying to use the same fixed IP (allocated dynamically by the DHCP server) as the recently deleted one.

Manual workaround: 
```
[root@openstack ~(keystone_a)]# service openstack-nova-network stop
[root@openstack ~(keystone_a)]# killall dnsmasq
[root@openstack ~(keystone_a)]# iptables -F
[root@openstack ~(keystone_a)]# service openstack-nova-network start

```

However, note that flushing all iptable rules can have unpredictable effects, esp. if you have a lot of instances running!

Nothing to fix. Assigning to @themisa

**Comment by abhimukh** [comment] 2015-07-29 13:58
@hansthen and @themisa This issue is identical to #296

**Comment by hansthen** [comment] 2015-08-14 14:02
I want to solve this issue here and not in #296. It turns out that the problem is caused by dnsmasq does not assign an IP address (quickly enough) when an IP address is reused after a VM was deleted.

**Comment by abhimukh** [comment] 2015-08-14 18:20
The root cause of the problem is the following: 
Nova does not allow dnsmasq to give out IPs dynamically. Rather, it updates the dhcp-hostsfile everytime a new instance is created with a the instance's assigned IP. It then sends a SIGHUP to dnsmasq to reread the dhcp-hostsfile. 

The problem is this does not update dnsmasq's lease cache. So, once in a while when nova chooses to "fill in the gap" i.e. assign an IP which was  previously assigned to a (now deleted instance), dnsmasq may not have had enough time to figure out that that instance is dead, and the IP should be released (note that the lease is for a day). 

This creates the race condition, when dnsmasq tries to figure if the allocated IP is still being used while the instance  is still booting up.

**Comment by abhimukh** [comment] 2015-08-14 18:24
Workarounds: sorted in ascending order of complexity

1. If you need to create and delete instances in quick succession, first create and then delete. if you need to transfer floating IPs, you can always first disassociate them without deleting the instance. The problem is due to conflicts in the fixed (internal) IPs

2. If you accidentally delete first, then, kill all dnamasq and restart nova network before creating the new instance (this will flush the leases ) 

3. Send a dhcp_release to the specific instance of dnsmasq to release the IP, before creating the new instance.

**Comment by hansthen** [comment] 2015-08-17 07:47
Okay, can we open a bug report upstream with the OpenStack people for this? Workaround is acceptable, but needs to be documented. @themisa can you make it part of the test procedures?

**Comment by abhimukh** [comment] 2015-08-17 12:05
I suggest (1) as the workaround and (2) and (3) only for troubleshooting.

**Comment by abhimukh** [comment] 2015-08-18 07:33
Reassigning to @themisa for testing and procedure documentation.

**Comment by themisa** [comment] 2015-08-25 12:13
Created a troubleshooting guide. Also another procedure for safely deleting login nodes and dissociating the floating ips.

**Closed by themisa** 2015-08-25 12:13 UTC
Labels: ASAP, bug
