### ISSUE TITLE
Assign a non-conflicting IP address to the docker bridge

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#254] opened 2015-05-21 11:32 UTC
The docker bridge on the controller uses IP addresses within the 172.16.0.0/22 range. This can conflict with IP ranges we use for the containers. We need to customize the docker bridge to use a different range. 

Please, see the discussion related to #224 for more information.

**Comment by hansthen** [comment] 2015-05-21 13:14
Duplicate of #218

**Closed by hansthen** 2015-05-21 13:14 UTC
