### ISSUE TITLE
No ipmi driver support in the controller node

### ISSUE THREAD

**Issue by brunopereira81** [clustervision/trinity#503] opened 2015-11-09 14:57 UTC
Seems that by default there is no IPMI support installed in the controller:

> [root@controller(magdeburg*) mgmtd]# service ipmi start
Redirecting to /bin/systemctl start  ipmi.service
Failed to issue method call: Unit ipmi.service failed to load: No such file or directory.
[root@controller(magdeburg*) mgmtd]# ipmitool-xcat sel list
Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
Get SEL Info command failed

After installing proper support the bmc from the headnode can be accessed locally:

> [root@controller(magdeburg*) mgmtd]# ipmitool-xcat sel list
   1 | 10/07/2015 | 14:14:43 | OS Boot #0x07 | 
   2 | 10/07/2015 | 14:27:09 | OS Boot #0x08 | 
   3 | 10/07/2015 | 15:00:33 | OS Boot #0x07 | 
   4 | 10/07/2015 | 15:12:56 | OS Boot #0x08 | 
   5 | 10/07/2015 | 16:28:39 | OS Boot #0x07 | 
   6 | 10/07/2015 | 16:41:12 | OS Boot #0x08 | 

* (detached from vMagdeburg)
269bf23

**Comment by brunopereira81** [comment] 2015-11-09 15:05
Apparently also in all the nodes, same issue, not local IPMI support available.

**Comment by hansthen** [comment] 2015-11-11 22:14
@brunopereira81 Why do you need this?

**Comment by brunopereira81** [comment] 2015-11-12 10:07
Among others:

- Troubleshoot node's hardware locally and without draining the node / rebooting it;
- Configure bmc's that failed to be configured properly by xCAT's bmcsetup script;
- Change IPMI sensor thresholds during node booting (required for some nodes that report hardware issues when there are none).

I could go on but this seems like a good policy to add to nodes some support for the possibility of doing these things locally instead of remotely would you not agree?

**Comment by hansthen** [comment] 2015-11-18 20:08
**Version:** cc03c73
**Environment:** amaster

I am unable to reproduce this on the controller.
```
[root@controller-1(amaster*) ~]# ipmitool-xcat sel list | head
  7f | 10/03/2015 | 17:20:28 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
  80 | 10/03/2015 | 17:20:34 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
  81 | 10/03/2015 | 17:20:37 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
  82 | 10/03/2015 | 17:20:39 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
  83 | 10/03/2015 | 17:20:39 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
  84 | 10/03/2015 | 17:20:44 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
  85 | 10/03/2015 | 17:20:48 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
  86 | 10/03/2015 | 17:20:50 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
  87 | 10/03/2015 | 17:20:55 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
  88 | 10/03/2015 | 17:20:57 | Memory | Correctable ECC | Asserted | CPU 0 DIMM 8
``` 
For the trinity nodes, I am not convinced yet we need local ipmi client support. We want to keep the node images minimal and actively discourage people to login to the physical nodes. There are easy solutions to access ipmi on the nodes (use remote ipmi/boot the node into the genesis kernel).

**Comment by brunopereira81** [comment] 2015-11-19 13:49
If you are saying that amaster is a new fresh controller then I think we can drop it. It might have fixed itself in some way on another release, it was not present in * (detached from vMagdeburg) 269bf23.

**Comment by hansthen** [comment] 2015-11-21 05:00
Closing issue, as we have local ipmi support in the genesis kernel.

**Closed by hansthen** 2015-11-21 05:00 UTC
Labels: enhancement, invalid
