### ISSUE TITLE
cv_configure_xcat dereferences symbolic links when copying modules from master

### ISSUE THREAD

**Issue by quentinleburel** [clustervision/trinity#702] opened 2016-04-20 08:18 UTC
**Version:** r8 1b911a6
**Environment:** 140781

```
[root@controller-1(140781*) ~]# grep trinity/clustervision /xcatpost/cv_configure_xcat
cp -LrT /tmp/trinity/clustervision /trinity/clustervision &
```

This is not correct, this is what is causing the controllers running out of disk space and installation taking forever

It also explains the discrepancy between disk usage on master and on controller:
```
[root@controller-1(140781*) ~]# du -sh /trinity/clustervision/
79G     /trinity/clustervision/
[root@pmaster 7]# du -sh /trinity/clustervision/
11G     /trinity/clustervision/

```

**Comment by hansthen** [comment] 2016-04-22 23:14
Duplicate of #710.

**Closed** 2016-05-15 05:36 UTC
Labels: bug, duplicate, Tested
