### ISSUE TITLE
Colander: NFS server not running on the controller

### ISSUE THREAD

**Issue by abhimukh** [clustervision/trinity#448] opened 2015-09-22 12:08 UTC
```
[root@controller-2(amaster) ~]# cat /trinity/version
* colander
22487d1

[root@controller-2(amaster) ~]# netstat -plunt | grep nfs
[root@controller-2(amaster) ~]# showmount -e
clnt_create: RPC: Port mapper failure - Unable to receive: errno 111 (Connection refused)

[root@controller-2(amaster) ~]# ssh node003
Last login: Tue Sep 22 14:05:50 2015 from controller-2.cluster
[root@openstack ~]# mount | egrep '(home|trinity|cluster)'
[root@openstack ~]# 

```

**Comment by hansthen** [comment] 2015-09-24 05:43
Duplicate of 450.

**Closed** 2015-10-02 13:23 UTC
Labels: duplicate, r6
