### ISSUE TITLE
trinity nodes not running docker on boot

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#57] opened 2015-02-12 16:19 UTC
**Software:** Trinity
**Component:** netboot trinity image, or controller
**Hardware:**  controller03-->node04
**Test case:** 1.2.5  Docker containers are running on trinity nodes
**Bug description:** Trinity nodes should be running containers when booted, but are not
**Steps to reproduce bug:**
1) netboot a node with a Trinity image (nodeset nodeXX osimage=<>
2) rpower nodeXX reset
3) docker images
**Expected output:**

**Actual output**
-bash: docker: command not found

**Comment by themisa** [comment] 2015-02-12 16:20
see #50

**Comment by hansthen** [comment] 2015-02-17 14:24
Problem is in the genimage. Docker needs to be added to the repo, but we have problems with that (see #35.) As a workaround you can use the commands `yum install docker --downloadonly --destdir /install/centos7.0/x86_64/Packages/; createrepo /install/centos7.0/x86_64/Packages/`

**Comment by hansthen** [comment] 2015-02-17 14:24
Duplicate of #35

**Closed by hansthen** 2015-02-17 14:24 UTC
Labels: bug, duplicate
