### ISSUE TITLE
Login node creation: no /cluster/apps and /cluster/modulefiles

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#185] opened 2015-04-13 19:22 UTC
**version:** 618ba29

After creating the login node for vc-a, no apps and modulefiles directories were created.
```
[root@c001 ~]# ls /cluster
etc
```

**Comment by hansthen** [comment] 2015-04-13 19:24
Did not check against vc-b yet.

**Comment by hansthen** [comment] 2015-04-13 19:24
Workaround: create manually.

**Comment by abhimukh** [comment] 2015-04-14 08:03
This is a duplicate of #148 and #167. Already fixed in b0d04ea

**Comment by abhimukh** [comment] 2015-04-14 08:08
Further comment: The modulefiles and apps directories are created by the API server when HPC resources are added to the cluster for the first time. Since, the first resource allocation for vc-a is not done by the API server, the aforementioned directories are not created. 

The modulefiles and apps directories for vc-a should be in the repo (just like the /cluster/etc/vc-a/slurm directory).

**Comment by themisa** [comment] 2015-04-20 08:22
to test this, need to reprovision controller.

**Comment by abhimukh** [comment] 2015-04-21 10:01
This issue should be fixed now. Reassigning @themisa

**Comment by themisa** [comment] 2015-04-22 08:50
[root@c001 /]# cat /etc/resolv.conf 
nameserver 10.141.255.254
search vc-b
[root@c001 /]# ls /cluster
apps  etc  modulefiles

**Comment by themisa** [comment] 2015-04-22 08:52
* r3
f877aca

**Closed by themisa** 2015-04-22 08:52 UTC
Labels: bug
