### ISSUE TITLE
controller installation: cv_install_xcat_ws can't find xcat commands

### ISSUE THREAD

**Issue by themisa** [clustervision/trinity#243] opened 2015-05-19 08:15 UTC
**Software:** master_installer 6739973
**Component:** install controller
**Hardware:** SM controller02
**Test case:** 1.1.3
**Bug description:**
Even though cv_install_xcat is called before cv_install_xcat_ws , we get the following error

```
./cv_install_xcat_ws: line 15: tabch: command not found
./cv_install_xcat_ws: line 16: mkdef: command not found

```

**Steps to reproduce:**
nodeset controller
ssh to controller
cat /var/log/xcat/xcat.log | grep -i "found"

**Comment by abhimukh** [comment] 2015-05-21 10:39
This is a problem with cv_install_xcat. Either xcat did not get installed properly or /etc/profile.d/xcat.sh was not sourced. 

Reassigning to @hansthen

**Comment by hansthen** [comment] 2015-05-21 11:45
I was unable to reproduce this. However, it may be that sometimes package installation starts in a postscript before the network is up. Reassigning to Themis to see if the problem is persistent.

**Comment by themisa** [comment] 2015-05-21 11:49
Yes, persistent * master_installer
42c4bc2
```
================================================================================
 Package  Arch    Version                  Repository                      Size
================================================================================
Installing:
 mod_ssl  x86_64  1:2.4.6-31.el7.centos    local-centos7.0-x86_64-x86_64   99 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 99 k
Installed size: 220 k
Is this ok [y/d/N]: Exiting on user command
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2015-05-21.13-45.67bxvt.yumtx
Redirecting to /bin/systemctl restart  httpd.service
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package perl-JSON-2.59-2.el7.noarch already installed and latest version
Nothing to do
Changing password for user trinity.
passwd: all authentication tokens updated successfully.
./cv_install_xcat_ws: line 15: tabch: command not found
./cv_install_xcat_ws: line 16: mkdef: command not found
```

**Comment by themisa** [comment] 2015-05-27 14:59
Not fixed in: * r3
f4eec01
./cv_install_xcat_ws: line 15: tabch: command not found
./cv_install_xcat_ws: line 16: mkdef: command not found

**Comment by themisa** [comment] 2015-05-27 15:23
correct file not in /install/postscripts

**Comment by hansthen** [comment] 2015-05-27 18:39
See #275 as well, to avoid this type of error in the future.

**Comment by themisa** [comment] 2015-05-28 09:38
Fixed in * r3
0d12eb5

Need to make sure its merged in master_installer/r4

**Closed** 2015-06-01 12:47 UTC
Labels: bug, QA verified
