### ISSUE TITLE
Environment modules: missing path entries

### ISSUE THREAD

**Issue by hansthen** [clustervision/trinity#235] opened 2015-05-13 11:40 UTC
Module files should also search for module files in /cluster/modulefiles.

```
#/usr/share/Modules/your_contribs                       # Edit for your requirements
/trinity/clustervision/modulefiles
/cluster/modulefiles
```

**Comment by hansthen** [comment] 2015-05-13 11:40
And this should be shared between login node and containers.

**Comment by abhimukh** [comment] 2015-05-22 11:24
This is fixed in 284cdee83831ee9bcaeb6f6aeb279908e729c9d1

**Comment by themisa** [comment] 2015-05-29 13:45
duplicate of #250

**Closed by themisa** 2015-05-29 13:45 UTC
Labels: duplicate, enhancement
